In [38]:
import numpy as np

test_array = np.array([[1,2,3], [4,5,6], [7,8,9]])

np.random.seed(0)
first_centroid_index = np.random.choice(len(test_array))

centroids_arr = test_array[first_centroid_index]
test_array = np.delete(test_array, first_centroid_index, 0)

print(test_array)
print(centroids_arr)


[[4 5 6]
 [7 8 9]]
[1 2 3]


In [41]:
import pandas as pd

test_df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [71,81,91]])

first_cen_index = np.random.choice(len(test_df))

# test_df["sum"] = test_df.sum(axis=1)
# np.linalg.norm(test_df[0])
#  test_df["min_dist"] = test_df.apply(lambda row: )

a = [[12, 13, 14], [6,7,8]]
test_df["distance"] = test_df.apply(lambda row: min(np.linalg.norm(i - row) for i in a), axis=1) # 2
test_df["ratio"] = test_df["distance"] / sum(test_df["distance"])                # 3
print(test_df)
print("------")
print(np.random.choice(len(test_df), list(test_df["ratio"])))



SyntaxError: unexpected EOF while parsing (1003577456.py, line 17)